### ISSUE TITLE
Choose Workshops

### ISSUE THREAD

**Issue by sjawhar** [sjawhar/mothership-energy-transition#2]
We can request business and/or technical workshops from the organizers. Please review the list in [this doc](https://drive.google.com/open?id=1brR7uym5-MJoy5-eK8ViTFw-wnWLZr5Z) and identify workshops that you think are relevant for us (e.g. skills we are currently lacking).

**Comment by QuantumLove** [comment]
He @sjawhar,

Looking good our board,
Cannot move these myself though, I think only you have permissions.

Just came here to 🎏 it!
